module_order:
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "*_R[12]_001_fastqc.zip"
        - "*_R[12]_fastqc.zip"
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results after adapter trimming."
      target: ""
      path_filters:
        - "*_R[12]_001.trimmed_fastqc.zip"
        - "*_R[12].trimmed_fastqc.zip"
  - fastp
  - star
  - salmon

report_section_order:
  fastqc_trimmed:
    before: fastqc_raw
